In [1]:
import pandas as pd

In [4]:
# Cria um dicionário com autores, preços e títulos:
dictionary = {'Autores': [ 'Rick Riordan', 'J. R. R. Tolkien', 'Rick Riordan', 'Machado de Assis'],
              'Títulos': [ 'O Ladrão de Raios', 'A Sociedade doAnel', 'Mar de Monstros', 'Mémorias Postumas de Brás Cubas'],
              'Preços': [41.2, 35.7, 39.5,40.5]}

In [5]:
## DataFrame
df = pd.DataFrame(dictionary)

In [6]:
df

            Autores                          Títulos  Preços
0      Rick Riordan                O Ladrão de Raios    41.2
1  J. R. R. Tolkien               A Sociedade doAnel    35.7
2      Rick Riordan                  Mar de Monstros    39.5
3  Machado de Assis  Mémorias Postumas de Brás Cubas    40.5

In [7]:
df['Autores'] [1]

'J. R. R. Tolkien'

In [9]:
    df['Autores']

0        Rick Riordan
1    J. R. R. Tolkien
2        Rick Riordan
3    Machado de Assis
Name: Autores, dtype: object

In [12]:
df['Preços'].mean()

39.225

In [13]:
df['Preços']

0    41.2
1    35.7
2    39.5
3    40.5
Name: Preços, dtype: float64

In [14]:
mascara = (df['Autores'] == 'Rick Riordan')

In [15]:
print (mascara)

0     True
1    False
2     True
3    False
Name: Autores, dtype: bool

In [16]:
df [mascara]

        Autores            Títulos  Preços
0  Rick Riordan  O Ladrão de Raios    41.2
2  Rick Riordan    Mar de Monstros    39.5

In [25]:
df = df.append({'Autores': 'Rick Riordan', 'Títulos' : 'A Maldiça do Titã', 'Preços': 40.20}, ignore_index = True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [26]:
print (df)

            Autores                          Títulos  Preços
0      Rick Riordan                O Ladrão de Raios    41.2
1  J. R. R. Tolkien               A Sociedade doAnel    35.7
2      Rick Riordan                  Mar de Monstros    39.5
3  Machado de Assis  Mémorias Postumas de Brás Cubas    40.5